#连接数据库
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/health?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
#mybatis别名
mybatis:
  type-aliases-package: com.zjc.pojo
  mapper-locations: classpath:mapper/*.xml

dubbo:
  application:
    name: health_server
  registry:
    address: zookeeper://localhost:2181
  protocol:
    name: dubbo
    port: 20881
  scan: com.zjc.service.impl


server:
  port: 18082




###端口号
#  server.port=8880
#
#  ## Dubbo 服务提供者配置
#  spring.dubbo.application.name=dubbo_server
#  spring.dubbo.registry.address=zookeeper://39.108.123.128:2181
#  spring.dubbo.protocol.name=dubbo
#  spring.dubbo.protocol.port=20880
#  spring.dubbo.scan=com.dalaoyang.dubbo

